name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install dependencies
        run: npm i

      - name: Build folders for npm
        run: npm run build
        env:
          CI: true

      - name: Fix package.json
        run: npm run pre:publish

      - name: Set publishing config
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: NPM Publish Main
        run: npm publish
